version: 2.1
jobs:
  build-image:
    machine: true
    working_directory: ~/src
    parameters:
      dockerfile:
        type: string
      tag-prefix:
        type: string
      publish:
        type: boolean
      image-name:
        type: string

    steps:
      - checkout
      - run:
          name: Get CircleCI runner
          command: tools/get-circleci-runner.sh
      - run:
          name: Setup Qemu
          command: |
            sudo apt-get update && sudo apt-get install -y --no-install-recommends qemu-user-static binfmt-support qemu-system-arm
            sudo update-binfmts --enable qemu-arm
            sudo update-binfmts --enable qemu-aarch64
            sudo update-binfmts --display qemu-arm
            sudo update-binfmts --display qemu-aarch64
            cp /usr/bin/qemu-arm-static $(pwd)
            cp /usr/bin/qemu-aarch64-static $(pwd)
      - run:
          name: Build Docker Image - << parameters.dockerfile >>
          command: |
            docker build . -t electron-<< parameters.image-name >>-image -f << parameters.dockerfile >>
            docker tag electron-<< parameters.image-name >>-image ghcr.io/electron/<< parameters.image-name >>:<< parameters.tag-prefix>>latest
            docker tag electron-<< parameters.image-name >>-image ghcr.io/electron/<< parameters.image-name >>:<< parameters.tag-prefix >>$CIRCLE_SHA1

      - when:
          condition: << parameters.publish >>
          steps:
            - run:
                name: Push Docker Image
                command: |
                  echo "$GITHUB_TOKEN" | docker login  ghcr.io -u "$GITHUB_USER" --password-stdin
                  docker push ghcr.io/electron/<< parameters.image-name >>

orbs:
  docker: circleci/docker@0.5.17

workflows:
  version: 2.1
  build:
    jobs:
      - build-image:
          name: publish-x64
          dockerfile: Dockerfile
          tag-prefix: ''
          image-name: build
          publish: true
          filters:
            branches:
              only:
                - main
      - build-image:
          name: publish-devcontainer
          dockerfile: Dockerfile.devcontainer
          tag-prefix: ''
          image-name: devcontainer
          publish: true
          filters:
            branches:
              only:
                - main
      - build-image:
          name: publish-arm32v7
          dockerfile: Dockerfile.arm32v7
          tag-prefix: arm32v7-
          image-name: build
          publish: true
          filters:
            branches:
              only:
                - main
      - build-image:
          name: publish-arm64v8
          dockerfile: Dockerfile.arm64v8
          tag-prefix: arm64v8-
          image-name: build
          publish: true
          filters:
            branches:
              only:
                - main
      - build-image:
          name: build-x64
          dockerfile: Dockerfile
          tag-prefix: ''
          image-name: build
          publish: false
          filters:
            branches:
              ignore:
                - main
      - build-image:
          name: build-devcontainer
          dockerfile: Dockerfile.devcontainer
          tag-prefix: ''
          image-name: devcontainer
          publish: false
          filters:
            branches:
              ignore:
                - main
      - build-image:
          name: build-arm32v7
          dockerfile: Dockerfile.arm32v7
          tag-prefix: arm32v7-
          image-name: build
          publish: false
          filters:
            branches:
              ignore:
                - main
      - build-image:
          name: build-arm64v8
          dockerfile: Dockerfile.arm64v8
          tag-prefix: arm64v8-
          image-name: build
          publish: false
          filters:
            branches:
              ignore:
                - main


